### ISSUE TITLE
Long titles in doc overflow sidebar (and look generally weird)

### ISSUE THREAD

**Issue by christophajohns** [jgori-ouistiti/CoopIHC#10]
**Describe the bug**
In the sphinx docs, both the pointing and the eye module names overflow the sidebar bounds and are generally too long. They should probably be moved into their own section of the docs (e.g. Task and Agent Collections) anyways.

**To Reproduce**
1. Go to [the docs](https://jgori-ouistiti.github.io/CoopIHC/index.html)
2. See the sidebar
3. Scroll down to 'Pointing Module. This module is used to model pointing tasks.' and 'Eye Module. This module is used to model eye movements of human observers.'
4. See error (overflow)

**Expected behavior**
You would expect the name to be separated into name and description or title and subtitle. Alternatively, you would perhaps expect these parts of the docs to be in another section like Task and Agent Collections entirely.

**Screenshots**

**Desktop:**
 - OS: MacOS
 - Browser Safari
 - Version 15.1

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/31001349/143435008-76e93e0b-bb2f-49e8-ba5b-5aecdd9684dc.png">

**Comment by jgori-ouistiti** [comment]
After many changes to the doc, this seems to no longer be an issue
