### ISSUE TITLE
tikzpictures don't render correctly in published docs

### ISSUE THREAD

**Issue by christophajohns** [jgori-ouistiti/CoopIHC#11]
**Describe the bug**
In the published docs (in contrast to local preview), the tikzpictures, for example [illustrating the interaction model](https://jgori-ouistiti.github.io/CoopIHC/guide/interaction_model.html), seem to be displayed incorrectly. This causes the entire pages where they should be included to be incorrectly displayed.

**To Reproduce**
1. Go to the [docs (interaction model)](https://jgori-ouistiti.github.io/CoopIHC/guide/interaction_model.html)
2. Scroll down to 'System Message'
3. See error

**Expected behavior**
The tikzpictures should be render with the appropriate size and position.

<img width="1051" alt="image" src="https://user-images.githubusercontent.com/31001349/143435932-c7ffd435-a8a8-4873-bcf6-1cd306ff1b50.png">

**Screenshots**

**Desktop:**
 - OS: macOS
 - Browser: Safari
 - Version: 15.1

<img width="1051" alt="image" src="https://user-images.githubusercontent.com/31001349/143436760-2c1565c4-8a6f-4ab2-977b-251f53480062.png">
<img width="1051" alt="image" src="https://user-images.githubusercontent.com/31001349/143436785-09288724-d6fe-4312-b280-6f220a3aeb57.png">

**Comment by jgori-ouistiti** [comment]
solved with PR #36
