### ISSUE TITLE
Home page of docs is difficult to read

### ISSUE THREAD

**Issue by christophajohns** [jgori-ouistiti/CoopIHC#12]
As of now, the home page of the docs is quite text-heavy and difficult to read. It includes a lot of headers, subheaders and lists that get the same visual weight. Maybe this could be simplified, for example using the interaction model figure, using notes and warnings or by curating the displayed content more heavily.

**Comment by jgori-ouistiti** [comment]
I think the home page looks okay now. Could be better, but for now I'll close the issue. Please raise a more precise issue if  you still feel it is not okay
