### ISSUE TITLE
ModelChecks and task-and-agent collection bloat core

### ISSUE THREAD

**Issue by christophajohns** [jgori-ouistiti/CoopIHC#13]
As of now, the `ModelChecks` bundle as well as the directories implementing some form of an interaction (task and agents) that build on top of core are quite separate from the main contribution of the library. They are rather separate parts that build on top of the existing core. If the library were published as a package, both the model checks and the task-and-agent collections could be moved into their own repos to keep the core slim.

**Comment by jgori-ouistiti** [comment]
I agree that we should separate the task-and-agent collection and modelcheck parts of the library to two separate repositories.

**Comment by jgori-ouistiti** [comment]
modelchecks has now a repo at https://github.com/jgori-ouistiti/CoopIHC-modelchecks

**Comment by christophajohns** [comment]
Task and agents collection was moved to https://github.com/jgori-ouistiti/CoopIHC-zoo. See also #20

**Comment by christophajohns** [comment]
PR to move model checks content to https://github.com/christophajohns/CoopIHC-modelchecks has been approved and merged. See #19

**Comment by christophajohns** [comment]
Some of the dependencies from these two code bases still need to be removed from the core and docs requirements files I think

**Comment by christophajohns** [comment]
> PR to move model checks content to https://github.com/christophajohns/CoopIHC-modelchecks has been approved and merged. See #19

CoopIHC-ModelChecks has now been published as a package to [PyPI](https://pypi.org/project/CoopIHC-ModelChecks/) in a very basic form.

**Comment by jgori-ouistiti** [comment]
I think PR #52 removed any outstanding code from modelchecks and zoo, closing this issue
