### ISSUE TITLE
Unclear instructions to setup development

### ISSUE THREAD

**Issue by christophajohns** [jgori-ouistiti/CoopIHC#2]
### Problem

Currently, the documentation in the README and using Sphinx does not completely detail **how to set up your environment to contribute to the library**.

### Advantages

Adding clear instructions how to set up a development environment would...

- ...make it easier to contribute to the library,
- ...reduce the risk of errors due to differences in versions or dependencies,
- ...provide a reasonable environment specification for running tests.

### Requirements

We should establish clear steps and instructions about the following points:

- [ ] Name the version of Python that is supported by the library.
- [ ] Have *one* list of dependencies that is complete, only containing modules in use and is being kept up to date.

### Further Development

At a later stage, considering [dockerization](https://hackernoon.com/how-to-dockerize-any-application-b60ad00e76da) could provide additional ease of use and clarity to the development setup process.

**Comment by jgori-ouistiti** [comment]
I've edited the readme to say that we are using pipenv. I've also committed the pipfiles, which contain all dependencies as well as supported Python version. I'm closing the issue
