### ISSUE TITLE
documentation is inconsistent

### ISSUE THREAD

**Issue by jgori-ouistiti** [jgori-ouistiti/CoopIHC#22]
Overall the documentation is inconsistent/outdated

- [x] documentation from modelchecks is still here
- [x] examples in the documentation use pointing and eye modules without imports from the new repositories
- [x] many outdated files

**Comment by christophajohns** [comment]
I think the model checks documentation is gone now, right? We can mark that task as done, the others of course not yet.

**Comment by jgori-ouistiti** [comment]
I think so to

**Comment by jgori-ouistiti** [comment]
All tasks here are more or less done. The only thing that remains is the more complex example that has not been updated yet. I'll file a separate issue for that
