### ISSUE TITLE
Test files are outdated

### ISSUE THREAD

**Issue by christophajohns** [jgori-ouistiti/CoopIHC#23]
**Describe the bug**
Many of the files in the `test` directory seem to be outdated and should likely be removed or updated. This seems like a good opportunity to discuss a common test strategy in general.

**To Reproduce**
1. Run, for example, `test/test_bundle.py`
2. See error

**Expected behavior**
We should introduce at least class-wise unit testing and very basic integration testing for the simple examples in the docs to make sure that we don't introduce breaking changes to published examples and guides.

**Comment by christophajohns** [comment]
@jgori-ouistiti When you are thinking about profiling, this could be a good place to start. When you start writing unit and integration tests, you have to make your code snippets run independently anyways, which offers a natural starting point for performance testing (e.g. using timeit) as well. Maybe I can help write some tests too.

**Comment by jgori-ouistiti** [comment]
Yes both items are the most important imo right now. (as well as a fix to the API, see issue #31 -- but that should be fairly quick to do). Some of the tests can be written from the examples located in coopihc/examples/simple_examples

**Comment by jgori-ouistiti** [comment]
I've opened a branch 'test' for this purpose. I we are going to work on this branch together, let's coordinate a bit beforehand

**Comment by christophajohns** [comment]
Sure, sounds good. I guess it would make sense to start "inside-out", meaning, there are probably some very core functions that are being called all the time (e.g. in `BaseAgent`, `InteractionTask` etc.). If we can create solid tests for those first, that should already cover a lot of relevant use cases. We can then move outwards from there to more niche functions and classes.

**Comment by jgori-ouistiti** [comment]
Yes that was also my intention. For example, I'm handling issue #31 and will start writing tests relative to those needs. E.g. changing the signature for BaseAgent will lead me to write a test for BaseAgent. Let's make sure we regularly push to test so that we don't end up writing the same tests.

**Comment by jgori-ouistiti** [comment]
Writing comprehensive tests is obviously tedious, although necessary, and I'm taking some shortcuts to deal with other priorities. Below is a list of those that we may want to address later

- [ ] comparison test in the stateelement test only tests for __eq__, not other methods.

**Comment by jgori-ouistiti** [comment]
Fixed in PR #52
