### ISSUE TITLE
Contributing file still on pipenv instead of poetry

### ISSUE THREAD

**Issue by christophajohns** [jgori-ouistiti/CoopIHC#41]
The repo seems to have switched to poetry as the package manager. It does, however, not mention how to setup the repo for development using poetry in the contributing guide. There, it still mentions pipenv and a non-existent requirements file.

On a related note, I don‘t know how to setup the repo for local development and testing. How do I install the package (e.g. pip3 install . -e) without a setup file?

**Comment by jgori-ouistiti** [comment]
The contributing.md now mentions the poetry setup, as well as a link to the pip install -e question on the poetry repo. I've added the setup.py in the repo, which for now has to be updated by hand (i.e. by running poetry build, and extracting the setup from the tarball).

**Comment by christophajohns** [comment]
Installing with poetry failed on scipy 1.6.1. Upgrading to the latest version (1.7.3) fixed the issue (after many, many headaches).

**Comment by jgori-ouistiti** [comment]
I've update the toml file to have scipy = '^1.7.3' and pushed on main branch

**Comment by jgori-ouistiti** [comment]
After some back and forth, I had to change the pyptoject.toml file for this to work with setuptools for a local install with pip -e flag.  This works now
