### ISSUE TITLE
StateElement  "numpy switch" 

### ISSUE THREAD

**Issue by jgori-ouistiti** [jgori-ouistiti/CoopIHC#42]
**Is your feature request related to a problem? Please describe.**
Currently, StateElement is a collection of a numpy.array and a Space object. Most numpy operations should work on StateElement without touching Space, so it would be nice to have the ability to directly call numpy methods on a StateElement

**Describe the solution you'd like**
The StateElement __getattr__ method had a numpy switch, which, when some method applied to StateElement is not found will look for one with the same name in Numpy. This has never worked, I think, but the idea of catching the calls that fail on StateElement and see whether there is a method with the same name in numpy, and apply it to the values of StateElement should work.

**Describe alternatives you've considered**
explicitly apply these operations to the StateElement values instead of the StateElement object

**Additional context**

**Comment by christophajohns** [comment]
Removed commented out code from PR #47. Pasted here for reference:

```python
# Numpy switch, Not working, see Issue 42
import sys

def __getattr__(self, key):
    _np = sys.modules["numpy"]
    print(_np, key, getattr(_np, key))
    if hasattr(_np, key):
        # adapted from https://stackoverflow.com/questions/13776504/how-are-arguments-passed-to-a-function-through-getattr
        def wrapper(*args, **kwargs):
            return getattr(_np, key)(self.values, *args, **kwargs)

        return wrapper

    raise AttributeError(
        "StateElement does not have attribute {}. Tried to fall back to numpy but it also did not have this attribute".format(
            key
        )
    )
```

**Comment by jgori-ouistiti** [comment]
PR #52 deals with this, by having StateElement subclass numpy ndarray. The __array_ufunc__ mechanism has been overriden, which casts StateElements to numpy ndarray, applies the numpy function, and recasts back to StateElement. For other numpy functions which are not ufunc, the _array_function__ dispatching mechanism is used. By default, a numpy function applied to a StateElement will operate on itself (but cast as array), but this behavior can be easily changed with a decorator that is provided. This issue will be closed when PR# 52 is merged
