### ISSUE TITLE
dic argument in InteractionTask.reset() might not be necessary

### ISSUE THREAD

**Issue by christophajohns** [jgori-ouistiti/CoopIHC#44]
In the `reset` method of `InteractionTask`, there is an argument called `dic` that can likely be removed. This would make it easier to implement a subclass for `InteractionTask` and would make the code leaner. If this is implemented, however, we would need to update the `reset` method for all subclasses of `InteractionTask` currently in the code and docs (incl. coopihczoo and coopihc-modelchecks) to reflect this change.

https://github.com/jgori-ouistiti/CoopIHC/blob/42d1905ce724f2f7c5d6ffc81e0b401dfb7919a7/coopihc/interactiontask/InteractionTask.py#L189

**Comment by christophajohns** [comment]
From Julien:

> The reset() function is never called by the end-user; the end-user will call reset on Bundle, which will call the task's base reset with the relevant dic.
> The super().reset() calls should be removed in coopihczoo, because that mechanism has been replaced by the base_reset_mechanism. So it shouldn't be a problem. I'm updating coopihczoo at the moment actually, because many things are broken there; that is just one example. In general I would suggest that whenever you think there is some change that might break coopihczoo, please go ahead anyway, but file an issue in coopihczoo so that I am aware of it. Maybe you can create a special template for this type of issue if you think that is necessary, since these would be "expected bugs" rather than an actual bug.

**Comment by jgori-ouistiti** [comment]
CoopIHC code is now updated, closing this issue
