### ISSUE TITLE
StateElement accepts single argument for spaces, but Space needs array_list

### ISSUE THREAD

**Issue by christophajohns** [jgori-ouistiti/CoopIHC#45]
When creating a subclass to `InteractionTask`, you can set a state as a `StateElement`. The `ExampleTask` does so by passing a single `Space` to the `StateElement`'s `spaces` argument. This is allowed. `Space`, however, does not accept anything but a list of `numpy.ndarray`s. In case of a one-dimensional state/space, it might be more readable, if the following code would also work:

`self.state[self.X] = StateElement(values=0, spaces=Space(numpy.array([-1, 0, 1])))`

Right now, it causes an error that `array_list` needs to be a `numpy.ndarray`:

`Input argument array_list must be or must inherit from numpy.ndarray instance.`

Let me know what you think.

**Comment by jgori-ouistiti** [comment]
I agree that on the whole the interface of StateElement is a little bit complex, and it is a bit tedious to instantiate simple substates. I think this would be a good change indeed. We might also add shortcuts, maybe something like space.box(1, [-1,1]) would create a StateElement(values=1, spaces = Space([numpy.array([-1], dtype = numpy.float32), numpy.array([1]), dtype = numpy.float32]), and others. Opening this as #46. Leaving this issue open for the error message which is not really saying the right thing.
