### ISSUE TITLE
Short description missing from About field

### ISSUE THREAD

**Issue by christophajohns** [jgori-ouistiti/CoopIHC#5]
The repo is currently missing a short description in the About field on the code page. Changing this could improve discoverability and visibility. 

Example descriptions based on the docs can be found below:

> Common description of computational HCI contexts with Python.

> Component-based interaction environments for computational HCI with Python.

> Generic components for computational human-computer interaction with Python.

**Comment by jgori-ouistiti** [comment]
Tentative description:
Two-agent component-based interaction environments for computational HCI with Python
