### ISSUE TITLE
Missing issue template

### ISSUE THREAD

**Issue by christophajohns** [jgori-ouistiti/CoopIHC#6]
To make it easier for other developers to contribute to the library, it could be beneficial to create an [issue template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository). It could, for example, be based on the structure in #2 (Problem, Advantages, Tasks, Further Development).

**Comment by jgori-ouistiti** [comment]
I've added default bug reports and features requests, is that enough or do you think another type of issue is needed?

**Comment by christophajohns** [comment]
Seems like a great start! Closing the issue.
