### ISSUE TITLE
Editor and linter settings not specified

### ISSUE THREAD

**Issue by christophajohns** [jgori-ouistiti/CoopIHC#7]
In order to make development and contribution more efficient (especially setting up the environment), it would be good to specify the linter and editor settings both in the `CONTRIBUTING.md` file and in, for example, a `.vscode/settings.json` file.

**Comment by jgori-ouistiti** [comment]
see updated CONTRIBUTIONS.md and close if appropriate

**Comment by christophajohns** [comment]
Looks good for now! Closing the issue
