### ISSUE TITLE
Docs are missing complete API Reference

### ISSUE THREAD

**Issue by christophajohns** [jgori-ouistiti/CoopIHC#8]
### Problem

Currently, the sphinx documentation does not contain a full API Reference that can be searched and be used to debug the in-code doc strings.

### Advantages

By adding a full API Reference, developers could...

- ...easily search the code from the docs,
- ...debug docstrings,
- ...link to the API Reference from other parts of the docs.

**Comment by jgori-ouistiti** [comment]
The plan is to use sphinx directives (autodoc, automodule etc.) which extract the API info from the correctly formatted docstring. I will close this issue once the docs and dosctrings are updated, and the docstring format is specified in the contributing.md file

**Comment by jgori-ouistiti** [comment]
The dosctring format is now specified in the contributing.md file, but the actual dosctrings still need to be written

**Comment by christophajohns** [comment]
To me it seems that even a partial API Reference would be beneficial at this point. So, I would propose to add those parts to the sphinx docs already but keep the issue open. I think the model checks parts already have the necessary docstrings. What do you think?

**Comment by jgori-ouistiti** [comment]
PR autosummary working for an API reference entry in the docs #26 scaffolds the solution. It is just a matter of writing and verifying docstrings now. While the API is not somewhat reliable, I'm leaving the issue open

**Comment by jgori-ouistiti** [comment]
PR #28  closes

**Comment by jgori-ouistiti** [comment]
solved some problems with the API reference, but docstrings still not updated

**Comment by jgori-ouistiti** [comment]
solved by PR #38
