### ISSUE TITLE
To do lists and notes scattered in published docs

### ISSUE THREAD

**Issue by christophajohns** [jgori-ouistiti/CoopIHC#9]
Currently, there are several stumps of articles, to do lists and notes around the published docs. Since we have started tracking to dos, feature requests and bugs in GitHub issues now, maybe these can be moved from the docs into separate issues instead. At this point, even one large issue per to do list would be beneficial. You can always create smaller issues that link to those bigger ones. As a result, the docs would likely be easier to read and maintain.

**Comment by jgori-ouistiti** [comment]
this has been sorted out by various commits over the time
